package localization.auth;

import java.util.HashMap;
import java.util.Map;

public class AuthLocalization {
    private static final Map<String, String> en = new HashMap<>();
    private static final Map<String, String> ru = new HashMap<>();
    private static final Map<String, String> kz = new HashMap<>();

    static {
        // English
        en.put("ACCESS_DENIED", "Access denied: Only OR or DEPARTMENT managers can access this menu.");
        en.put("MANAGER_MENU_TITLE", "Manager Menu");
        en.put("APPROVE_REGISTRATIONS", "Approve Course Registrations");
        en.put("ASSIGN_TEACHERS", "Assign Teachers to Courses");
        en.put("ASSIGN_LESSON_TO_STUDENT", "Assign Lesson to Student");
        en.put("UPDATE_LESSON_TIME", "Update Lesson Time for Student");
        en.put("VIEW_COMPLAINTS", "View Complaints");
        en.put("OPEN_NEWS_MENU", "Open News Menu");
        en.put("UNKNOWN_OPTION", "Unknown Option");
        en.put("APPROVING_REGISTRATIONS", "Approving registrations...");
        en.put("ASSIGNING_TEACHERS", "Assigning teachers...");
        en.put("ENTER_STUDENT_ID", "Enter Student ID:");
        en.put("STUDENT_NOT_FOUND", "Student not found.");
        en.put("ENTER_DAY", "Enter the day of the week (e.g., MONDAY):");
        en.put("ENTER_LESSON_NAME", "Enter the lesson name:");
        en.put("ENTER_LESSON_TIME", "Enter the time for the lesson (e.g., 14:00 - 16:00):");
        en.put("ENTER_LESSON_TYPE", "Enter the type of lesson (L for Lecture, P for Practice):");
        en.put("INVALID_LESSON_TYPE", "Invalid lesson type. Please enter L or P.");
        en.put("LESSON_ASSIGNED_SUCCESS", "Lesson assigned successfully:");
        en.put("TO_STUDENT", "to student");
        en.put("ON_DAY", "on day");
        en.put("INVALID_DAY", "Invalid day of the week.");
        en.put("ENTER_CURRENT_DAY", "Enter the current day of the lesson (e.g., MONDAY):");
        en.put("ENTER_NEW_DAY", "Enter the new day of the lesson (e.g., TUESDAY):");
        en.put("ENTER_NEW_TIME", "Enter the new time for the lesson (e.g., 14:00 - 16:00):");
        en.put("LESSON_UPDATED_SUCCESS", "Lesson updated successfully.");
        en.put("PERMISSION_DENIED", "Permission denied: Only DEPARTMENT managers can view complaints.");
        en.put("NO_COMPLAINTS", "No complaints found.");
        en.put("COMPLAINTS_FOR_MANAGER", "Complaints for Manager with ID:");
        en.put("NEWS_MENU_TITLE", "---- News Menu ----");
        en.put("VIEW_EXISTING_NEWS", "View Existing News");
        en.put("ADD_NEWS", "Add News");
        en.put("INPUT_NEWS_TITLE", "Input title for news:");
        en.put("INPUT_NEWS_CONTENT", "Input content for news:");
        en.put("INPUT_NEWS_PRIORITY", "Input priority:");
        en.put("RESEARCHER_MENU_TITLE", "==== Researcher Menu ====");
        en.put("VIEW_ALL_RESEARCH", "View All Research Papers");
        en.put("ADD_RESEARCH", "Add a New Research Paper");
        en.put("VIEW_SPECIFIC_RESEARCH", "View a Specific Research Paper");
        en.put("ALL_RESEARCH", "--- All Research Papers ---");
        en.put("NO_RESEARCH_AVAILABLE", "No research papers available.");
        en.put("RESEARCH_DETAILS", "ID: {ID}, Title: {TITLE}, Citations: {CITATIONS}");
        en.put("ENTER_RESEARCH_ID", "Enter Research Paper ID:");
        en.put("ENTER_RESEARCH_TITLE", "Enter Research Paper Title:");
        en.put("ENTER_RESEARCH_CITATIONS", "Enter Number of Citations:");
        en.put("RESEARCH_ADDED_SUCCESS", "Research paper added successfully!");
        en.put("ENTER_RESEARCH_ID_TO_VIEW", "Enter the ID of the Research Paper you want to view:");
        en.put("RESEARCH_NOT_FOUND", "Research paper not found.");
        en.put("RESEARCH_DETAILS_HEADER", "--- Research Paper Details ---");
        en.put("COURSE_MENU_TITLE", "==== Course Menu ====");
        en.put("VIEW_AVAILABLE_COURSES", "View Available Courses");
        en.put("VIEW_ENROLLED_COURSES", "View Enrolled Courses");
        en.put("APPLY_FOR_COURSE", "Apply for a Course");
        en.put("AVAILABLE_COURSES_TITLE", "--- Available Courses ---");
        en.put("NO_COURSES_AVAILABLE", "No courses available.");
        en.put("ENTER_COURSE_ID", "Enter Course ID to register:");
        en.put("COURSE_APPLICATION_SUCCESS", "Course application submitted successfully!");
        en.put("ERROR_PREFIX", "Error:");
        en.put("ENROLLED_COURSES_TITLE", "--- Enrolled Courses ---");
        en.put("NO_ENROLLED_COURSES", "No enrolled courses.");
        en.put("STUDENT_MENU_TITLE", "Student Menu");
        en.put("VIEW_MARKS", "View Marks");
        en.put("REGISTER_FOR_COURSE", "Register for a Course");
        en.put("VIEW_RESEARCH_PAPERS", "View Research Papers");
        en.put("VIEW_SCHEDULE", "View Schedule");
        en.put("VIEW_AVAILABLE_LESSONS", "View Available Lessons");
        en.put("ADD_LESSON_TO_SCHEDULE", "Add Lesson to Schedule");
        en.put("VIEW_TRANSCRIPT", "View Transcript");
        en.put("OPEN_RESEARCHER_MENU", "Open Researcher Menu");
        en.put("TALK_TO_GUIDEON_BOT", "Talk to Guideon Bot");
        en.put("MANAGE_ORGANIZATIONS", "Manage Organizations");
        en.put("YOUR_MARKS", "--- Your Marks ---");
        en.put("NO_MARKS", "You have no marks yet.");
        en.put("AVAILABLE_COURSES", "--- Available Courses ---");
        en.put("SELECT_COURSE", "Enter the number of the course to register:");
        en.put("COURSE_REGISTER_SUCCESS", "Successfully registered for the course: ");
        en.put("INVALID_SELECTION", "Invalid selection.");
        en.put("YOUR_RESEARCH_PAPERS", "--- Your Research Papers ---");
        en.put("YOUR_SCHEDULE", "--- Your Weekly Schedule ---");
        en.put("AVAILABLE_LESSONS", "--- Available Lessons ---");
        en.put("NO_REGISTERED_COURSES", "You are not registered for any courses. Register first to view lessons.");
        en.put("COURSE_PREFIX", "Course: ");
        en.put("SELECT_COURSE_TO_VIEW", "Enter the number of the course to view lessons:");
        en.put("SELECT_LESSON_TO_ADD", "Enter the number of the lesson to add:");
        en.put("LESSON_ADD_SUCCESS", "Lesson added to schedule successfully!");
        en.put("GUIDEON_BOT_TITLE", "--- Guideon Bot ---");
        en.put("GUIDEON_PROMPT", "Ask a question about rooms, departments, or university-related information:");
        en.put("YOU", "You");
        en.put("GUIDEON_EXIT", "Exiting Guideon Bot. Returning to the main menu.");
        en.put("GUIDEON", "Guideon");
        en.put("RESEARCHER_MENU", "--- Researcher Menu ---");
        en.put("TRANSCRIPT", "--- Transcript ---");
        en.put("MANAGE_ORGANIZATIONS_TITLE", "--- Manage Organizations ---");
        en.put("JOIN_ORGANIZATION", "Join an Organization");
        en.put("LEAVE_ORGANIZATION", "Leave an Organization");
        en.put("VIEW_JOINED_ORGANIZATIONS", "View Joined Organizations");
        en.put("BACK_TO_MENU", "Back to Menu");
        en.put("SELECT_OPTION", "Select an option:");
        en.put("RETURNING_TO_MENU", "Returning to main menu...");
        en.put("AVAILABLE_ORGANIZATIONS", "--- Available Organizations ---");
        en.put("ENTER_ORGANIZATION_NAME", "Enter the name of the organization:");
        en.put("ORGANIZATION_JOIN_SUCCESS", "Organization joined successfully!");
        en.put("INVALID_ORGANIZATION_NAME", "Invalid organization name.");
        en.put("JOINED_ORGANIZATIONS", "--- Joined Organizations ---");
        en.put("NO_JOINED_ORGANIZATIONS", "You are not a member of any organizations.");
        en.put("ORGANIZATION_LEAVE_SUCCESS", "Organization left successfully!");
        en.put("GRADEBOOK_MENU_TITLE", "--- Grade Book for Course");
        en.put("VIEW_STUDENTS", "View Students");
        en.put("ADD_MARK", "Add Mark");
        en.put("VIEW_STUDENT_MARKS", "View Student Marks");
        en.put("NO_STUDENTS", "No students registered for this course.");
        en.put("STUDENTS_FOR_COURSE", "Students for Course");
        en.put("NAME", "Name");
        en.put("SELECT_MARK_TYPE", "Select Mark Type:");
        en.put("FIRST_ATTESTATION", "1st Attestation");
        en.put("SECOND_ATTESTATION", "2nd Attestation");
        en.put("FINAL", "Final");
        en.put("INVALID_CHOICE", "Invalid choice. Returning to menu.");
        en.put("ENTER_SCORE", "Enter Score");
        en.put("INVALID_SCORE", "Invalid score. Score must be between");
        en.put("MARKS_FOR_COURSE", "Marks for Course");
        en.put("STUDENT_ID", "Student ID");
        en.put("NO_MARKS_FOUND", "No marks found for this student in this course.");
        en.put("MARK_ADDED_SUCCESS", "Mark added successfully.");
        en.put("COURSE_ID", "Course ID");
        en.put("TEACHER_MENU_TITLE", "==== Teacher Menu ====");
        en.put("VIEW_STATUS", "View Status");
        en.put("OPEN_GRADE_BOOK", "Open Grade Book");
        en.put("SEND_COMPLAINT", "Send a Complaint");
        en.put("TEACHER_STATUS", "--- Teacher Status ---");
        en.put("PROFESSOR", "Professor");
        en.put("RESEARCHER", "Researcher");
        en.put("YES", "Yes");
        en.put("NO", "No");
        en.put("INVALID_COURSE_ID", "Invalid Course ID. Please try again.");
        en.put("ENTER_ACCUSED_ID", "Enter the ID of the accused (Student)");
        en.put("ACCUSED_NOT_FOUND", "Accused user not found or not a student. Please try again.");
        en.put("ENTER_COMPLAINT_DETAILS", "Enter complaint details");
        en.put("SELECT_URGENCY_LEVEL", "Select urgency level");
        en.put("LOW", "Low");
        en.put("MEDIUM", "Medium");
        en.put("HIGH", "High");
        en.put("ENTER_MANAGER_ID", "Enter the manager ID to whom the complaint is being sent");
        en.put("COMPLAINT_SENT", "Complaint sent successfully!");
        en.put("BACK", "Back");
        en.put("INVALID_OPTION", "Invalid option. Please try again.");
        en.put("ERROR_OCCURRED", "An error occurred");
        en.put("INVALID_INPUT", "Invalid input. Please enter a number.");
        en.put("ADMIN_MENU_TITLE", "==== Admin Menu ====");
        en.put("VIEW_ALL_USERS", "View All Users");
        en.put("ADD_NEW_USER", "Add a New User");
        en.put("REMOVE_USER", "Remove a User");
        en.put("VIEW_LOG_FILES", "View Log Files");
        en.put("GET_USER_BY_ID", "Get User by ID");
        en.put("ENTER_USER_TYPE", "Enter User Type (admin, manager, researcher, teacher, master, phd, bachelor)");
        en.put("ENTER_USER_ID", "Enter User ID");
        en.put("ENTER_USER_NAME", "Enter User Name");
        en.put("ENTER_USER_EMAIL", "Enter User Email");
        en.put("ENTER_USER_PASSWORD", "Enter User Password");
        en.put("USER_ADDED_SUCCESS", "User added successfully!");
        en.put("ENTER_USER_ID_TO_REMOVE", "Enter User ID to Remove");
        en.put("USER_REMOVED_SUCCESS", "User removed successfully!");
        en.put("ENTER_USER_ID_TO_RETRIEVE", "Enter User ID to Retrieve");
        en.put("USER_NOT_FOUND", "No user found with ID");
        en.put("LOGIN_PROMPT", "Please log in.");
        en.put("ENTER_EMAIL", "Enter your email:");
        en.put("ENTER_PASSWORD", "Enter your password:");
        en.put("INVALID_CREDENTIALS", "Invalid email or password.");
        en.put("WELCOME_USER", "Welcome");
        en.put("OPEN_RESEARCHER_MENU", "Open Researcher Menu");

// Russian
        ru.put("ACCESS_DENIED", "Доступ запрещён: Только менеджеры OR или DEPARTMENT могут получить доступ к этому меню.");
        ru.put("MANAGER_MENU_TITLE", "Меню менеджера");
        ru.put("APPROVE_REGISTRATIONS", "Подтвердить регистрацию на курсы");
        ru.put("ASSIGN_TEACHERS", "Назначить преподавателей на курсы");
        ru.put("ASSIGN_LESSON_TO_STUDENT", "Назначить урок студенту");
        ru.put("UPDATE_LESSON_TIME", "Обновить время урока для студента");
        ru.put("VIEW_COMPLAINTS", "Посмотреть жалобы");
        ru.put("OPEN_NEWS_MENU", "Открыть меню новостей");
        ru.put("UNKNOWN_OPTION", "Неизвестный вариант");
        ru.put("APPROVING_REGISTRATIONS", "Подтверждение регистраций...");
        ru.put("ASSIGNING_TEACHERS", "Назначение преподавателей...");
        ru.put("ENTER_STUDENT_ID", "Введите ID студента:");
        ru.put("STUDENT_NOT_FOUND", "Студент не найден.");
        ru.put("ENTER_DAY", "Введите день недели (например, ПОНЕДЕЛЬНИК):");
        ru.put("ENTER_LESSON_NAME", "Введите название урока:");
        ru.put("ENTER_LESSON_TIME", "Введите время урока (например, 14:00 - 16:00):");
        ru.put("ENTER_LESSON_TYPE", "Введите тип урока (Л для Лекции, П для Практики):");
        ru.put("INVALID_LESSON_TYPE", "Неверный тип урока. Пожалуйста, введите Л или П.");
        ru.put("LESSON_ASSIGNED_SUCCESS", "Урок успешно назначен:");
        ru.put("TO_STUDENT", "студенту");
        ru.put("ON_DAY", "в день");
        ru.put("INVALID_DAY", "Неверный день недели.");
        ru.put("ENTER_CURRENT_DAY", "Введите текущий день урока (например, ПОНЕДЕЛЬНИК):");
        ru.put("ENTER_NEW_DAY", "Введите новый день урока (например, ВТОРНИК):");
        ru.put("ENTER_NEW_TIME", "Введите новое время урока (например, 14:00 - 16:00):");
        ru.put("LESSON_UPDATED_SUCCESS", "Урок успешно обновлен.");
        ru.put("PERMISSION_DENIED", "Доступ запрещён: Только менеджеры DEPARTMENT могут просматривать жалобы.");
        ru.put("NO_COMPLAINTS", "Жалобы не найдены.");
        ru.put("COMPLAINTS_FOR_MANAGER", "Жалобы для менеджера с ID:");
        ru.put("NEWS_MENU_TITLE", "---- Меню новостей ----");
        ru.put("VIEW_EXISTING_NEWS", "Просмотреть существующие новости");
        ru.put("ADD_NEWS", "Добавить новость");
        ru.put("INPUT_NEWS_TITLE", "Введите заголовок новости:");
        ru.put("INPUT_NEWS_CONTENT", "Введите содержание новости:");
        ru.put("INPUT_NEWS_PRIORITY", "Введите приоритет:");
        ru.put("RESEARCHER_MENU_TITLE", "==== Меню исследователя ====");
        ru.put("VIEW_ALL_RESEARCH", "Просмотреть все научные работы");
        ru.put("ADD_RESEARCH", "Добавить новую научную работу");
        ru.put("VIEW_SPECIFIC_RESEARCH", "Просмотреть определённую научную работу");
        ru.put("ALL_RESEARCH", "--- Все научные работы ---");
        ru.put("NO_RESEARCH_AVAILABLE", "Научных работ нет.");
        ru.put("RESEARCH_DETAILS", "ID: {ID}, Название: {TITLE}, Цитирования: {CITATIONS}");
        ru.put("ENTER_RESEARCH_ID", "Введите ID научной работы:");
        ru.put("ENTER_RESEARCH_TITLE", "Введите название научной работы:");
        ru.put("ENTER_RESEARCH_CITATIONS", "Введите количество цитирований:");
        ru.put("RESEARCH_ADDED_SUCCESS", "Научная работа успешно добавлена!");
        ru.put("ENTER_RESEARCH_ID_TO_VIEW", "Введите ID научной работы для просмотра:");
        ru.put("RESEARCH_NOT_FOUND", "Научная работа не найдена.");
        ru.put("RESEARCH_DETAILS_HEADER", "--- Детали научной работы ---");
        ru.put("COURSE_MENU_TITLE", "==== Меню курсов ====");
        ru.put("VIEW_AVAILABLE_COURSES", "Просмотреть доступные курсы");
        ru.put("VIEW_ENROLLED_COURSES", "Просмотреть зарегистрированные курсы");
        ru.put("APPLY_FOR_COURSE", "Подать заявку на курс");
        ru.put("AVAILABLE_COURSES_TITLE", "--- Доступные курсы ---");
        ru.put("NO_COURSES_AVAILABLE", "Нет доступных курсов.");
        ru.put("COURSE_APPLICATION_SUCCESS", "Заявка на курс успешно отправлена!");
        ru.put("ERROR_PREFIX", "Ошибка:");
        ru.put("ENROLLED_COURSES_TITLE", "--- Зарегистрированные курсы ---");
        ru.put("NO_ENROLLED_COURSES", "Нет зарегистрированных курсов.");
        ru.put("STUDENT_MENU_TITLE", "Меню студента");
        ru.put("VIEW_MARKS", "Просмотр оценок");
        ru.put("REGISTER_FOR_COURSE", "Регистрация на курс");
        ru.put("VIEW_RESEARCH_PAPERS", "Просмотр научных работ");
        ru.put("VIEW_SCHEDULE", "Просмотр расписания");
        ru.put("VIEW_AVAILABLE_LESSONS", "Просмотр доступных занятий");
        ru.put("ADD_LESSON_TO_SCHEDULE", "Добавить занятие в расписание");
        ru.put("VIEW_TRANSCRIPT", "Просмотр ведомости");
        ru.put("TALK_TO_GUIDEON_BOT", "Поговорить с ботом Гидеон");
        ru.put("MANAGE_ORGANIZATIONS", "Управление организациями");
        ru.put("YOUR_MARKS", "--- Ваши оценки ---");
        ru.put("NO_MARKS", "У вас пока нет оценок.");
        ru.put("AVAILABLE_COURSES", "--- Доступные курсы ---");
        ru.put("SELECT_COURSE", "Введите номер курса для регистрации:");
        ru.put("COURSE_REGISTER_SUCCESS", "Успешно зарегистрированы на курс: ");
        ru.put("INVALID_SELECTION", "Неверный выбор.");
        ru.put("YOUR_RESEARCH_PAPERS", "--- Ваши научные работы ---");
        ru.put("YOUR_SCHEDULE", "--- Ваше недельное расписание ---");
        ru.put("AVAILABLE_LESSONS", "--- Доступные занятия ---");
        ru.put("NO_REGISTERED_COURSES", "Вы не зарегистрированы на курсы. Сначала зарегистрируйтесь, чтобы увидеть занятия.");
        ru.put("COURSE_PREFIX", "Курс: ");
        ru.put("SELECT_COURSE_TO_VIEW", "Введите номер курса для просмотра занятий:");
        ru.put("SELECT_LESSON_TO_ADD", "Введите номер занятия для добавления:");
        ru.put("LESSON_ADD_SUCCESS", "Занятие успешно добавлено в расписание!");
        ru.put("GUIDEON_BOT_TITLE", "--- Бот Гидеон ---");
        ru.put("GUIDEON_PROMPT", "Задайте вопрос о комнатах, отделах или информации, связанной с университетом:");
        ru.put("YOU", "Вы");
        ru.put("GUIDEON_EXIT", "Выход из бота Гидеон. Возвращение в главное меню.");
        ru.put("GUIDEON", "Гидеон");
        ru.put("RESEARCHER_MENU", "--- Меню исследователя ---");
        ru.put("TRANSCRIPT", "--- Ведомость ---");
        ru.put("MANAGE_ORGANIZATIONS_TITLE", "--- Управление организациями ---");
        ru.put("JOIN_ORGANIZATION", "Вступить в организацию");
        ru.put("LEAVE_ORGANIZATION", "Выйти из организации");
        ru.put("VIEW_JOINED_ORGANIZATIONS", "Просмотр организаций");
        ru.put("BACK_TO_MENU", "Назад в меню");
        ru.put("RETURNING_TO_MENU", "Возвращение в главное меню...");
        ru.put("AVAILABLE_ORGANIZATIONS", "--- Доступные организации ---");
        ru.put("ENTER_ORGANIZATION_NAME", "Введите название организации:");
        ru.put("ORGANIZATION_JOIN_SUCCESS", "Вы успешно вступили в организацию!");
        ru.put("INVALID_ORGANIZATION_NAME", "Неверное название организации.");
        ru.put("JOINED_ORGANIZATIONS", "--- Присоединённые организации ---");
        ru.put("NO_JOINED_ORGANIZATIONS", "Вы не состоите в организациях.");
        ru.put("ORGANIZATION_LEAVE_SUCCESS", "Вы успешно покинули организацию!");
        ru.put("GRADEBOOK_MENU_TITLE", "--- Оценочная ведомость по курсу");
        ru.put("VIEW_STUDENTS", "Просмотреть студентов");
        ru.put("ADD_MARK", "Добавить оценку");
        ru.put("VIEW_STUDENT_MARKS", "Просмотреть оценки студентов");
        ru.put("NO_STUDENTS", "На данный курс нет зарегистрированных студентов.");
        ru.put("STUDENTS_FOR_COURSE", "Студенты по курсу");
        ru.put("SELECT_MARK_TYPE", "Выберите тип оценки:");
        ru.put("FIRST_ATTESTATION", "1-я аттестация");
        ru.put("SECOND_ATTESTATION", "2-я аттестация");
        ru.put("FINAL", "Финальный");
        ru.put("ENTER_SCORE", "Введите оценку");
        ru.put("INVALID_SCORE", "Недопустимая оценка. Оценка должна быть в диапазоне");
        ru.put("MARKS_FOR_COURSE", "Оценки по курсу");
        ru.put("STUDENT_ID", "ID студента");
        ru.put("NO_MARKS_FOUND", "Для этого студента по данному курсу оценки не найдены.");
        ru.put("MARK_ADDED_SUCCESS", "Оценка успешно добавлена.");
        ru.put("COURSE_ID", "ID курса");
        ru.put("TEACHER_MENU_TITLE", "==== Меню преподавателя ====");
        ru.put("VIEW_STATUS", "Просмотреть статус");
        ru.put("OPEN_GRADE_BOOK", "Открыть ведомость");
        ru.put("SEND_COMPLAINT", "Отправить жалобу");
        ru.put("TEACHER_STATUS", "--- Статус преподавателя ---");
        ru.put("PROFESSOR", "Профессор");
        ru.put("RESEARCHER", "Исследователь");
        ru.put("YES", "Да");
        ru.put("NO", "Нет");
        ru.put("INVALID_COURSE_ID", "Неверный ID курса. Попробуйте ещё раз.");
        ru.put("ENTER_ACCUSED_ID", "Введите ID обвиняемого (студент)");
        ru.put("ACCUSED_NOT_FOUND", "Обвиняемый пользователь не найден или не является студентом. Попробуйте снова.");
        ru.put("ENTER_COMPLAINT_DETAILS", "Введите детали жалобы");
        ru.put("SELECT_URGENCY_LEVEL", "Выберите уровень срочности");
        ru.put("LOW", "Низкий");
        ru.put("MEDIUM", "Средний");
        ru.put("HIGH", "Высокий");
        ru.put("ENTER_MANAGER_ID", "Введите ID менеджера, которому отправляется жалоба");
        ru.put("COMPLAINT_SENT", "Жалоба успешно отправлена!");
        ru.put("BACK", "Назад");
        ru.put("INVALID_OPTION", "Неверный вариант. Попробуйте снова.");
        ru.put("ERROR_OCCURRED", "Произошла ошибка");
        ru.put("INVALID_INPUT", "Некорректный ввод. Введите число.");
        ru.put("ADMIN_MENU_TITLE", "==== Меню администратора ====");
        ru.put("VIEW_ALL_USERS", "Просмотреть всех пользователей");
        ru.put("ADD_NEW_USER", "Добавить нового пользователя");
        ru.put("REMOVE_USER", "Удалить пользователя");
        ru.put("VIEW_LOG_FILES", "Просмотреть журналы");
        ru.put("GET_USER_BY_ID", "Найти пользователя по ID");
        ru.put("ENTER_USER_TYPE", "Введите тип пользователя (admin, manager, researcher, teacher, master, phd, bachelor)");
        ru.put("ENTER_USER_ID", "Введите ID пользователя");
        ru.put("ENTER_USER_NAME", "Введите имя пользователя");
        ru.put("ENTER_USER_EMAIL", "Введите email пользователя");
        ru.put("ENTER_USER_PASSWORD", "Введите пароль пользователя");
        ru.put("USER_ADDED_SUCCESS", "Пользователь успешно добавлен!");
        ru.put("ENTER_USER_ID_TO_REMOVE", "Введите ID пользователя для удаления");
        ru.put("USER_REMOVED_SUCCESS", "Пользователь успешно удалён!");
        ru.put("ENTER_USER_ID_TO_RETRIEVE", "Введите ID пользователя для поиска");
        ru.put("USER_NOT_FOUND", "Пользователь с ID не найден");
        ru.put("LOGIN_PROMPT", "Пожалуйста, войдите.");
        ru.put("ENTER_EMAIL", "Введите ваш email:");
        ru.put("ENTER_PASSWORD", "Введите ваш пароль:");
        ru.put("INVALID_CREDENTIALS", "Неверный email или пароль.");
        ru.put("WELCOME_USER", "Добро пожаловать");
        ru.put("OPEN_RESEARCHER_MENU", "Открыть меню исследователя");
        en.put("SELECT_OPTION", "выберите опцию:");

// Kazakh
        kz.put("ACCESS_DENIED", "Қол жеткізу шектелген: Тек OR немесе DEPARTMENT менеджерлері бұл мәзірге кіре алады.");
        kz.put("MANAGER_MENU_TITLE", "Менеджер мәзірі");
        kz.put("APPROVE_REGISTRATIONS", "Курстарға тіркеуді мақұлдау");
        kz.put("ASSIGN_TEACHERS", "Оқытушыларды курстарға тағайындау");
        kz.put("ASSIGN_LESSON_TO_STUDENT", "Сабақты студентке тағайындау");
        kz.put("UPDATE_LESSON_TIME", "Студент үшін сабақ уақытын жаңарту");
        kz.put("VIEW_COMPLAINTS", "Шағымдарды қарау");
        kz.put("OPEN_NEWS_MENU", "Жаңалықтар мәзірін ашу");
        kz.put("APPROVING_REGISTRATIONS", "Тіркеулерді мақұлдау...");
        kz.put("ASSIGNING_TEACHERS", "Оқытушыларды тағайындау...");
        kz.put("ENTER_STUDENT_ID", "Студенттің ID енгізіңіз:");
        kz.put("STUDENT_NOT_FOUND", "Студент табылмады.");
        kz.put("ENTER_DAY", "Аптаның күнін енгізіңіз (мысалы, ДҮЙСЕНБІ):");
        kz.put("ENTER_LESSON_NAME", "Сабақтың атауын енгізіңіз:");
        kz.put("ENTER_LESSON_TIME", "Сабақ уақытын енгізіңіз (мысалы, 14:00 - 16:00):");
        kz.put("ENTER_LESSON_TYPE", "Сабақ түрін енгізіңіз (Д - дәріс, Т - тәжірибе):");
        kz.put("INVALID_LESSON_TYPE", "Жарамсыз сабақ түрі. Д немесе Т енгізіңіз.");
        kz.put("LESSON_ASSIGNED_SUCCESS", "Сабақ сәтті тағайындалды:");
        kz.put("TO_STUDENT", "студентке");
        kz.put("ON_DAY", "күні");
        kz.put("INVALID_DAY", "Жарамсыз күн.");
        kz.put("ENTER_CURRENT_DAY", "Сабақтың ағымдағы күнін енгізіңіз (мысалы, ДҮЙСЕНБІ):");
        kz.put("ENTER_NEW_DAY", "Сабақтың жаңа күнін енгізіңіз (мысалы, СЕЙСЕНБІ):");
        kz.put("ENTER_NEW_TIME", "Сабақтың жаңа уақытын енгізіңіз (мысалы, 14:00 - 16:00):");
        kz.put("LESSON_UPDATED_SUCCESS", "Сабақ сәтті жаңартылды.");
        kz.put("PERMISSION_DENIED", "Қол жеткізу шектелген: Тек DEPARTMENT менеджерлері шағымдарды көре алады.");
        kz.put("NO_COMPLAINTS", "Шағымдар табылмады.");
        kz.put("COMPLAINTS_FOR_MANAGER", "Менеджерге арналған шағымдар (ID):");
        kz.put("NEWS_MENU_TITLE", "---- Жаңалықтар мәзірі ----");
        kz.put("VIEW_EXISTING_NEWS", "Бар жаңалықтарды қарау");
        kz.put("ADD_NEWS", "Жаңалық қосу");
        kz.put("INPUT_NEWS_TITLE", "Жаңалықтың тақырыбын енгізіңіз:");
        kz.put("INPUT_NEWS_CONTENT", "Жаңалықтың мазмұнын енгізіңіз:");
        kz.put("INPUT_NEWS_PRIORITY", "Артықшылықты енгізіңіз:");
        kz.put("RESEARCHER_MENU_TITLE", "==== Зерттеуші мәзірі ====");
        kz.put("VIEW_ALL_RESEARCH", "Барлық ғылыми жұмыстарды қарау");
        kz.put("ADD_RESEARCH", "Жаңа ғылыми жұмыс қосу");
        kz.put("VIEW_SPECIFIC_RESEARCH", "Белгілі бір ғылыми жұмысты қарау");
        kz.put("ALL_RESEARCH", "--- Барлық ғылыми жұмыстар ---");
        kz.put("NO_RESEARCH_AVAILABLE", "Ғылыми жұмыстар жоқ.");
        kz.put("RESEARCH_DETAILS", "ID: {ID}, Атауы: {TITLE}, Дәйексөздер: {CITATIONS}");
        kz.put("ENTER_RESEARCH_ID", "Ғылыми жұмыс ID енгізіңіз:");
        kz.put("ENTER_RESEARCH_TITLE", "Ғылыми жұмыс атауын енгізіңіз:");
        kz.put("ENTER_RESEARCH_CITATIONS", "Дәйексөздер санын енгізіңіз:");
        kz.put("RESEARCH_ADDED_SUCCESS", "Ғылыми жұмыс сәтті қосылды!");
        kz.put("ENTER_RESEARCH_ID_TO_VIEW", "Көру үшін ғылыми жұмыс ID енгізіңіз:");
        kz.put("RESEARCH_NOT_FOUND", "Ғылыми жұмыс табылмады.");
        kz.put("RESEARCH_DETAILS_HEADER", "--- Ғылыми жұмыс туралы мәлімет ---");
        kz.put("COURSE_MENU_TITLE", "==== Курстар мәзірі ====");
        kz.put("VIEW_AVAILABLE_COURSES", "Қолжетімді курстарды қарау");
        kz.put("VIEW_ENROLLED_COURSES", "Тіркелген курстарды қарау");
        kz.put("APPLY_FOR_COURSE", "Курсқа өтініш беру");
        kz.put("AVAILABLE_COURSES_TITLE", "--- Қолжетімді курстар ---");
        kz.put("NO_COURSES_AVAILABLE", "Қолжетімді курстар жоқ.");
        kz.put("ENTER_COURSE_ID", "Тіркелу үшін курстың ID енгізіңіз:");
        kz.put("COURSE_APPLICATION_SUCCESS", "Курсқа өтініш сәтті жіберілді!");
        kz.put("ERROR_PREFIX", "Қате:");
        kz.put("ENROLLED_COURSES_TITLE", "--- Тіркелген курстар ---");
        kz.put("NO_ENROLLED_COURSES", "Тіркелген курстар жоқ.");
        kz.put("STUDENT_MENU_TITLE", "Студент мәзірі");
        kz.put("VIEW_MARKS", "Бағаларды көру");
        kz.put("REGISTER_FOR_COURSE", "Курсқа тіркелу");
        kz.put("VIEW_RESEARCH_PAPERS", "Ғылыми жұмыстарды көру");
        kz.put("VIEW_SCHEDULE", "Кестені көру");
        kz.put("VIEW_AVAILABLE_LESSONS", "Қолжетімді сабақтарды көру");
        kz.put("ADD_LESSON_TO_SCHEDULE", "Сабақты кестеге қосу");
        kz.put("VIEW_TRANSCRIPT", "Транскриптті көру");
        kz.put("OPEN_RESEARCHER_MENU", "Зерттеуші мәзірін ашу");
        kz.put("TALK_TO_GUIDEON_BOT", "Гидеон ботпен сөйлесу");
        kz.put("MANAGE_ORGANIZATIONS", "Ұйымдарды басқару");
        kz.put("YOUR_MARKS", "--- Сіздің бағаларыңыз ---");
        kz.put("NO_MARKS", "Сізде бағалар әлі жоқ.");
        kz.put("AVAILABLE_COURSES", "--- Қолжетімді курстар ---");
        kz.put("SELECT_COURSE", "Тіркелу үшін курс нөмірін енгізіңіз:");
        kz.put("COURSE_REGISTER_SUCCESS", "Сіз курсқа сәтті тіркелдіңіз: ");
        kz.put("INVALID_SELECTION", "Қате таңдау.");
        kz.put("YOUR_RESEARCH_PAPERS", "--- Сіздің ғылыми жұмыстарыңыз ---");
        kz.put("YOUR_SCHEDULE", "--- Сіздің апталық кестеңіз ---");
        kz.put("AVAILABLE_LESSONS", "--- Қолжетімді сабақтар ---");
        kz.put("NO_REGISTERED_COURSES", "Сіз курстарға тіркелмегенсіз. Сабақтарды көру үшін алдымен тіркеліңіз.");
        kz.put("COURSE_PREFIX", "Курс: ");
        kz.put("SELECT_COURSE_TO_VIEW", "Сабақтарды көру үшін курс нөмірін енгізіңіз:");
        kz.put("SELECT_LESSON_TO_ADD", "Қосу үшін сабақ нөмірін енгізіңіз:");
        kz.put("LESSON_ADD_SUCCESS", "Сабақ кестеге сәтті қосылды!");
        kz.put("GUIDEON_BOT_TITLE", "--- Гидеон бот ---");
        kz.put("GUIDEON_PROMPT", "Бөлмелер, бөлімдер немесе университет туралы сұрақ қойыңыз:");
        kz.put("YOU", "Сіз");
        kz.put("GUIDEON_EXIT", "Гидеон ботынан шығу. Негізгі мәзірге оралу.");
        kz.put("GUIDEON", "Гидеон");
        kz.put("RESEARCHER_MENU", "--- Зерттеуші мәзірі ---");
        kz.put("TRANSCRIPT", "--- Транскрипт ---");
        kz.put("MANAGE_ORGANIZATIONS_TITLE", "--- Ұйымдарды басқару ---");
        kz.put("JOIN_ORGANIZATION", "Ұйымға қосылу");
        kz.put("LEAVE_ORGANIZATION", "Ұйымнан шығу");
        kz.put("VIEW_JOINED_ORGANIZATIONS", "Қосылған ұйымдарды көру");
        kz.put("BACK_TO_MENU", "Мәзірге оралу");
        kz.put("SELECT_OPTION", "Опцияны таңдаңыз:");
        kz.put("RETURNING_TO_MENU", "Негізгі мәзірге оралу...");
        kz.put("AVAILABLE_ORGANIZATIONS", "--- Қолжетімді ұйымдар ---");
        kz.put("ENTER_ORGANIZATION_NAME", "Ұйым атауын енгізіңіз:");
        kz.put("ORGANIZATION_JOIN_SUCCESS", "Сіз ұйымға сәтті қосылдыңыз!");
        kz.put("INVALID_ORGANIZATION_NAME", "Жарамсыз ұйым атауы.");
        kz.put("JOINED_ORGANIZATIONS", "--- Қосылған ұйымдар ---");
        kz.put("NO_JOINED_ORGANIZATIONS", "Сіз ешқандай ұйымға қосылмағансыз.");
        kz.put("ORGANIZATION_LEAVE_SUCCESS", "Сіз ұйымнан сәтті шықтыңыз!");
        kz.put("GRADEBOOK_MENU_TITLE", "--- Курстың бағалау кітабы");
        kz.put("VIEW_STUDENTS", "Студенттерді көру");
        kz.put("ADD_MARK", "Баға қосу");
        kz.put("VIEW_STUDENT_MARKS", "Студенттердің бағаларын көру");
        kz.put("NO_STUDENTS", "Бұл курсқа тіркелген студенттер жоқ.");
        kz.put("STUDENTS_FOR_COURSE", "Курс бойынша студенттер");
        kz.put("NAME", "Аты");
        kz.put("SELECT_MARK_TYPE", "Баға түрін таңдаңыз:");
        kz.put("FIRST_ATTESTATION", "1-ші аттестация");
        kz.put("SECOND_ATTESTATION", "2-ші аттестация");
        kz.put("FINAL", "Қорытынды");
        kz.put("INVALID_CHOICE", "Жарамсыз таңдау. Мәзірге оралу.");
        kz.put("ENTER_SCORE", "Бағаны енгізіңіз");
        kz.put("INVALID_SCORE", "Жарамсыз баға. Баға 0 мен");
        kz.put("MARKS_FOR_COURSE", "Курс бойынша бағалар");
        kz.put("STUDENT_ID", "Студент ID");
        kz.put("NO_MARKS_FOUND", "Бұл студент үшін осы курс бойынша бағалар табылмады.");
        kz.put("MARK_ADDED_SUCCESS", "Баға сәтті қосылды.");
        kz.put("COURSE_ID", "Курс ID");
        kz.put("TEACHER_MENU_TITLE", "==== Мұғалім мәзірі ====");
        kz.put("VIEW_STATUS", "Мәртебені көру");
        kz.put("OPEN_GRADE_BOOK", "Бағалау кітабын ашу");
        kz.put("SEND_COMPLAINT", "Шағым жіберу");
        kz.put("TEACHER_STATUS", "--- Мұғалімнің мәртебесі ---");
        kz.put("PROFESSOR", "Профессор");
        kz.put("RESEARCHER", "Зерттеуші");
        kz.put("YES", "Иә");
        kz.put("NO", "Жоқ");
        kz.put("INVALID_COURSE_ID", "Жарамсыз курс ID. Қайтадан көріңіз.");
        kz.put("ENTER_ACCUSED_ID", "Айыпталушының ID енгізіңіз (Студент)");
        kz.put("ACCUSED_NOT_FOUND", "Айыпталушы пайдаланушы табылмады немесе студент емес. Қайта көріңіз.");
        kz.put("ENTER_COMPLAINT_DETAILS", "Шағымның мәліметтерін енгізіңіз");
        kz.put("SELECT_URGENCY_LEVEL", "Шұғылдық деңгейін таңдаңыз");
        kz.put("LOW", "Төмен");
        kz.put("MEDIUM", "Орташа");
        kz.put("HIGH", "Жоғары");
        kz.put("ENTER_MANAGER_ID", "Шағым жіберілетін менеджердің ID енгізіңіз");
        kz.put("COMPLAINT_SENT", "Шағым сәтті жіберілді!");
        kz.put("BACK", "Артқа");
        kz.put("INVALID_OPTION", "Қате нұсқа. Қайта көріңіз.");
        kz.put("ERROR_OCCURRED", "Қате пайда болды");
        kz.put("INVALID_INPUT", "Қате енгізу. Сан енгізіңіз.");
        kz.put("ADMIN_MENU_TITLE", "==== Әкімші мәзірі ====");
        kz.put("VIEW_ALL_USERS", "Барлық пайдаланушыларды қарау");
        kz.put("ADD_NEW_USER", "Жаңа пайдаланушы қосу");
        kz.put("REMOVE_USER", "Пайдаланушыны жою");
        kz.put("VIEW_LOG_FILES", "Журналдарды қарау");
        kz.put("GET_USER_BY_ID", "Пайдаланушыны ID бойынша табу");
        kz.put("ENTER_USER_TYPE", "Пайдаланушының түрін енгізіңіз (admin, manager, researcher, teacher, master, phd, bachelor)");
        kz.put("ENTER_USER_ID", "Пайдаланушының ID енгізіңіз");
        kz.put("ENTER_USER_NAME", "Пайдаланушының атын енгізіңіз");
        kz.put("ENTER_USER_EMAIL", "Пайдаланушының email енгізіңіз");
        kz.put("ENTER_USER_PASSWORD", "Пайдаланушының құпия сөзін енгізіңіз");
        kz.put("USER_ADDED_SUCCESS", "Пайдаланушы сәтті қосылды!");
        kz.put("ENTER_USER_ID_TO_REMOVE", "Жою үшін пайдаланушының ID енгізіңіз");
        kz.put("USER_REMOVED_SUCCESS", "Пайдаланушы сәтті жойылды!");
        kz.put("ENTER_USER_ID_TO_RETRIEVE", "Іздеу үшін пайдаланушының ID енгізіңіз");
        kz.put("USER_NOT_FOUND", "ID бойынша пайдаланушы табылмады");
        kz.put("LOGIN_PROMPT", "Жүйеге кіріңіз.");
        kz.put("ENTER_EMAIL", "Электрондық поштаңызды енгізіңіз:");
        kz.put("ENTER_PASSWORD", "Құпия сөзіңізді енгізіңіз:");
        kz.put("INVALID_CREDENTIALS", "Қате email немесе құпия сөз.");
        kz.put("WELCOME_USER", "Қош келдіңіз");
    }

    public static String getMessage(String key, String language) {
        if (key == null || language == null) {
            return "Invalid localization key or language.";
        }

        Map<String, String> localizationMap;
        switch (language) {
            case "RU":
                localizationMap = ru;
                break;
            case "KZ":
                localizationMap = kz;
                break;
            default:
                localizationMap = en;
                break;
        }

        return localizationMap.getOrDefault(key, "Message not found for key: " + key);
    }
}
